// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUMJj5aPOmazRSGa_ptWal3L3_kbWL0dE',
    appId: '1:151407112754:web:f6314268494be6902a422b',
    messagingSenderId: '151407112754',
    projectId: 'arcon-attendance',
    authDomain: 'arcon-attendance.firebaseapp.com',
    storageBucket: 'arcon-attendance.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo_JZle1j4ITnd-XScO2s5rH2JnPZ4-Sc',
    appId: '1:151407112754:android:bf7ca30920c631382a422b',
    messagingSenderId: '151407112754',
    projectId: 'arcon-attendance',
    storageBucket: 'arcon-attendance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__y_uAF9ysyljzTe7f4GCjd92blTeea8',
    appId: '1:151407112754:ios:643b27101fed3a582a422b',
    messagingSenderId: '151407112754',
    projectId: 'arcon-attendance',
    storageBucket: 'arcon-attendance.appspot.com',
    iosClientId: '151407112754-rhde4ko4tktrkein29jjpio6as4ag5do.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );
}
